name: Java CI with Maven - Test and package
on:
  pull_request: #ça c'est le pull_request <https://docs.github.com/fr/actions/reference/workflows-and-actions/workflow-syntax?utm_source=chatgpt.com>
    branches:
      - main
jobs: #se qui va faire
  BuildJava: #nom du job :Build Java
    name: Build Java
    runs-on: ubuntu-latest #OS ou execute le job
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Build with Maven #une commande pour teste class
        run: mvn -B verify sonar:sonar \
          -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-') \
          -Dsonar.organization=ceri-m1-devops \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}