name: Documentation

on:
  pull_request:
    types:
      - closed   # Ne se déclenche que lorsque la PR est fermée
  workflow_dispatch: # Permet aussi de lancer manuellement si besoin

jobs:
  build-doc:
    if: github.event.pull_request.merged == true  # Vérifie que la PR a bien été mergée
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate Javadoc with Maven
        run: mvn -B javadoc:javadoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
