name: Documentation

on:
  pull_request:
    types:
      - closed   # Ne se déclenche que lorsque la PR est fermée
  workflow_dispatch: # Permet aussi de lancer manuellement si besoin

jobs:
  build-doc:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ✅ Autorise le push vers gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'    # ✅ Corrigé (avant tu avais mis '17')
          distribution: 'temurin'

      - name: Generate Javadoc with Maven
        run: mvn -B javadoc:javadoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
